### PR TITLE
Implement log parser

### LINKED ISSUE #3: Add LogParser
We should have a `LogParser` struct that takes in a file path, reads the data, and then it outputs a `Vec<Log>`.

```rust
use memoir::*;

let mut Logs: Vec<Log> = LogParser {
    filepath: "current_log.log",
}

for i in Logs {
    println!("{}", i.level)
}
```

### PR DESCRIPTION
**Pull request by tylercritchlow**
## LogParser Struct:

Added a new struct LogParser with a new method that takes a file path and a parse_logs method to read and parse log entries from the specified file.
The parse_logs method processes each line, assuming a log format of "%d [%l] %m", and creates a Vec<Log>.

## Example Use Case:
Suppose you have a log file named "example_log.log" with the following content:

```
2023-11-15T10:30:00 [Info] Application started
2023-11-15T10:35:00 [Warning] Disk space low
2023-11-15T10:40:00 [Error] Database connection failed
2023-11-15T10:45:00 [Debug] Debugging information
```
You can use the LogParser to parse this log file and print the log levels:

```rs
use memoir::*;

fn main() {
    let logs: Vec<Log> = LogParser::new("example_log.log").parse_logs();

    for log in logs {
        println!("{}: {}", log.level, log.message);
    }
}
```
This would output:
```
Info: Application started
Warning: Disk space low
Error: Database connection failed
Debug: Debugging information
```

## Test Cases:

These have not been updated.

**Please review and provide feedback.**

### CODE REVIEW

**Comment by tylercritchlow** [comment]
Is this what you were thinking, if not I will edit the code @brodycritchlow

**Review by brodycritchlow — CHANGES_REQUESTED** [review]
Just a few things, remember that we can have different formats— so it should work with them also. Other than that it looks good. Also make sure the checks pass.

**Comment by tylercritchlow** [comment]
> Just a few things, remember that we can have different formats— so it should work with them also. Other than that it looks good. Also make sure the checks pass.

the checks don't pass since I haven't added a test for the new code yet 😊

**Comment by brodycritchlow** [comment]
`\b[A-Za-z\s]+\b`

**Comment by tylercritchlow** [comment]
https://prod.liveshare.vsengsaas.visualstudio.com/join?4A617A8BA3DB9395BB138D968574D8F42764

**Pull request merged**
